package org.troy.capstone.constants;

public enum UISizeControl {

    HEIGHT_PADDING(10),
    WIDTH_PADDING(10),
    
    LEFT_SIDE_MAIN_PAGE_WIDTH(550),
    RIGHT_SIDE_MAIN_PAGE_WIDTH(500),
    MAIN_PAGE_HEIGHT(800),
    
    SEARCH_BAR_WIDTH(LEFT_SIDE_MAIN_PAGE_WIDTH.value),
    SEARCH_BAR_HEIGHT(50),
    
    SEARCHED_ITEM_PAGINATION_WIDTH(LEFT_SIDE_MAIN_PAGE_WIDTH.value),
    SEARCHED_ITEM_PAGINATION_HEIGHT(MAIN_PAGE_HEIGHT.value - SEARCH_BAR_HEIGHT.value - 100),
    SEARCHED_ITEM_CONTAINER_WIDTH(SEARCHED_ITEM_PAGINATION_WIDTH.value),
    SEARCHED_ITEM_CONTAINER_HEIGHT(SEARCHED_ITEM_PAGINATION_HEIGHT.value),
    SEARCHED_ITEM_SPACING(5),
    
    SEARCHED_ITEM_PANEL_WIDTH(SEARCHED_ITEM_CONTAINER_WIDTH.value - WIDTH_PADDING.value * 2),
    SEARCHED_ITEM_PANEL_HEIGHT(150),
    
    ATTRIBUTED_ITEM_IMAGE_WIDTH(150),
    ATTRIBUTED_ITEM_IMAGE_HEIGHT(150),
    
    ATTRIBUTED_ITEM_CONTAINER_WIDTH(ATTRIBUTED_ITEM_IMAGE_WIDTH.value + 50),
    
    SEARCHED_ITEM_LABEL_MAX_WIDTH(SEARCHED_ITEM_PANEL_WIDTH.value - ATTRIBUTED_ITEM_IMAGE_WIDTH.value - WIDTH_PADDING.value * 3),
    
    FILTERS_CONTAINER_WIDTH(RIGHT_SIDE_MAIN_PAGE_WIDTH.value),
    FILTERS_CONTAINER_HEIGHT(MAIN_PAGE_HEIGHT.value / 2);

    private final int value;

    UISizeControl(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
