// Generated by delombok at Wed Mar 18 14:57:48 EDT 2026
package org.troy.capstone.entities;

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import org.troy.capstone.constants.TableColumnName;
import org.troy.capstone.constants.URL;
import org.troy.capstone.utils.Converters;
import net.datafaker.Faker;
import tech.tablesaw.api.Row;

/**
 * A shopping item with various attributes. Main entity of the application.
 */
public class Item {
    /**
     * Faker instance for generating random data
     */
    private static final Faker faker = new Faker();
    /**
     * Unique identifier for the item
     */
    private String id;
    /**
     * Index of the item in the collection
     */
    private short index;
    /**
     * URL of the item's image
     */
    private String imageUrl;
    /**
     * Name of the item
     */
    private String name;
    /**
     * Publisher of the item
     */
    private String publisher;
    /**
     * Description of the item
     */
    private String description;
    /**
     * Category of the item
     */
    private String category;
    /**
     * Tags associated with the item
     */
    private Set<String> tags;
    /**
     * Author of the item's photo
     */
    private String photoAuthor;
    /**
     * URL of the photo's author
     */
    private String photoAuthorUrl;
    /**
     * Price of the item
     */
    private float price;
    /**
     * Review score of the item
     */
    private float reviewScore;
    /**
     * Number of reviews for the item
     */
    private short reviewCount;
    /**
     * Quantity of the item in stock
     */
    private short stockQuantity;
    /**
     * Date the item was added to the collection
     */
    private Date dateAdded;

    /**
     * Returns the value of the specified attribute for this item. The attribute is determined by the provided TableColumnName enum value.
     * 
     * @pre column is not null and corresponds to a valid attribute of the Item class.
     * 
     * @param column An enum value representing the attribute to retrieve from this item.
     * @return The value of the specified attribute for this item, returned as an Object. The caller must cast result.
     * @throws IllegalArgumentException If the provided column does not correspond to a valid attribute of the Item class.
     */
    public Object getAttribute(TableColumnName column) {
        return switch (column) {
            case INDEX -> index;
            case ID -> id;
            case IMAGE_URL -> imageUrl;
            case NAME -> name;
            case PUBLISHER -> publisher;
            case DESCRIPTION -> description;
            case CATEGORY -> category;
            case TAGS -> tags;
            case PRICE -> price;
            case REVIEW_SCORE -> reviewScore;
            case REVIEW_COUNT -> reviewCount;
            case STOCK_QUANTITY -> stockQuantity;
            case DATE_ADDED -> dateAdded;
            case PHOTO_AUTHOR -> photoAuthor;
            case PHOTO_AUTHOR_URL -> photoAuthorUrl;
            case RELEVANCE -> null;
            //Relevance is not a part of the item class, but is added later during search query filtering
        };
    }

    /**
     * Generates a random Item object with realistic values for each attribute using the Faker library.
     * 
     * @return A randomly generated Item object with all attributes populated with realistic random values.
     */
    public static Item randomItem() {
        return Item.builder().imageUrl(URL.DEFAULT_IMAGE_URL.getUrl()).name(faker.commerce().productName()).publisher(faker.company().name()).description(String.join(" ", faker.lorem().sentences(2))).category(faker.commerce().department()).tags(Set.copyOf(faker.lorem().words(3))).price((float) faker.number().randomDouble(2, 5, 500)).reviewScore((float) faker.number().randomDouble(1, 1, 5)).reviewCount((short) faker.number().numberBetween(0, 1000)).stockQuantity((short) faker.number().numberBetween(0, 100)).dateAdded(Date.from(faker.timeAndDate().future(365, TimeUnit.DAYS))).photoAuthor(URL.DEFAULT_AUTHOR_NAME.getUrl()).photoAuthorUrl(URL.DEFAULT_AUTHOR_URL.getUrl()).id(faker.internet().uuid()).build();
    }

    /**
     * Creates an Item object from a tablesaw Row. The Row must contain columns corresponding to the attributes of the Item class.
     * 
     * @pre itemRow is not null and contains the expected columns for creating an Item (ID, Name, etc.).
     * 
     * @param itemRow A Row from a tablesaw Table containing item info.
     * @return An Item object created from the data in the provided Row.
     */
    public static Item fromRow(Row itemRow) {
        return Item.builder().index(itemRow.getShort(TableColumnName.INDEX.getColumnName())).imageUrl(itemRow.getString(TableColumnName.IMAGE_URL.getColumnName())).name(itemRow.getString(TableColumnName.NAME.getColumnName())).publisher(itemRow.getString(TableColumnName.PUBLISHER.getColumnName())).description(itemRow.getString(TableColumnName.DESCRIPTION.getColumnName())).category(itemRow.getString(TableColumnName.CATEGORY.getColumnName())).tags(new HashSet<>(Arrays.asList(itemRow.getString(TableColumnName.TAGS.getColumnName()).split(", ")))).price(itemRow.getFloat(TableColumnName.PRICE.getColumnName())).reviewScore(itemRow.getFloat(TableColumnName.REVIEW_SCORE.getColumnName())).reviewCount(itemRow.getShort(TableColumnName.REVIEW_COUNT.getColumnName())).stockQuantity(itemRow.getShort(TableColumnName.STOCK_QUANTITY.getColumnName())).id(itemRow.getString(TableColumnName.ID.getColumnName())).photoAuthor(itemRow.getString(TableColumnName.PHOTO_AUTHOR.getColumnName())).photoAuthorUrl(itemRow.getString(TableColumnName.PHOTO_AUTHOR_URL.getColumnName())).dateAdded(Converters.localDateToDate(itemRow.getDate(TableColumnName.DATE_ADDED.getColumnName()))).build();
    }

    /**
     * Creates a new {@code Item} instance.
     *
     * @param id Unique identifier for the item
     * @param index Index of the item in the collection
     * @param imageUrl URL of the item's image
     * @param name Name of the item
     * @param publisher Publisher of the item
     * @param description Description of the item
     * @param category Category of the item
     * @param tags Tags associated with the item
     * @param photoAuthor Author of the item's photo
     * @param photoAuthorUrl URL of the photo's author
     * @param price Price of the item
     * @param reviewScore Review score of the item
     * @param reviewCount Number of reviews for the item
     * @param stockQuantity Quantity of the item in stock
     * @param dateAdded Date the item was added to the collection
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    Item(final String id, final short index, final String imageUrl, final String name, final String publisher, final String description, final String category, final Set<String> tags, final String photoAuthor, final String photoAuthorUrl, final float price, final float reviewScore, final short reviewCount, final short stockQuantity, final Date dateAdded) {
        this.id = id;
        this.index = index;
        this.imageUrl = imageUrl;
        this.name = name;
        this.publisher = publisher;
        this.description = description;
        this.category = category;
        this.tags = tags;
        this.photoAuthor = photoAuthor;
        this.photoAuthorUrl = photoAuthorUrl;
        this.price = price;
        this.reviewScore = reviewScore;
        this.reviewCount = reviewCount;
        this.stockQuantity = stockQuantity;
        this.dateAdded = dateAdded;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ItemBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private short index;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String publisher;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String category;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Set<String> tags;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String photoAuthor;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String photoAuthorUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private float price;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private float reviewScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private short reviewCount;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private short stockQuantity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Date dateAdded;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ItemBuilder() {
        }

        /**
         * Unique identifier for the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * Index of the item in the collection
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder index(final short index) {
            this.index = index;
            return this;
        }

        /**
         * URL of the item's image
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * Name of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * Publisher of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder publisher(final String publisher) {
            this.publisher = publisher;
            return this;
        }

        /**
         * Description of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * Category of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * Tags associated with the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder tags(final Set<String> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * Author of the item's photo
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder photoAuthor(final String photoAuthor) {
            this.photoAuthor = photoAuthor;
            return this;
        }

        /**
         * URL of the photo's author
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder photoAuthorUrl(final String photoAuthorUrl) {
            this.photoAuthorUrl = photoAuthorUrl;
            return this;
        }

        /**
         * Price of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder price(final float price) {
            this.price = price;
            return this;
        }

        /**
         * Review score of the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder reviewScore(final float reviewScore) {
            this.reviewScore = reviewScore;
            return this;
        }

        /**
         * Number of reviews for the item
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder reviewCount(final short reviewCount) {
            this.reviewCount = reviewCount;
            return this;
        }

        /**
         * Quantity of the item in stock
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder stockQuantity(final short stockQuantity) {
            this.stockQuantity = stockQuantity;
            return this;
        }

        /**
         * Date the item was added to the collection
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item.ItemBuilder dateAdded(final Date dateAdded) {
            this.dateAdded = dateAdded;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Item build() {
            return new Item(this.id, this.index, this.imageUrl, this.name, this.publisher, this.description, this.category, this.tags, this.photoAuthor, this.photoAuthorUrl, this.price, this.reviewScore, this.reviewCount, this.stockQuantity, this.dateAdded);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Item.ItemBuilder(id=" + this.id + ", index=" + this.index + ", imageUrl=" + this.imageUrl + ", name=" + this.name + ", publisher=" + this.publisher + ", description=" + this.description + ", category=" + this.category + ", tags=" + this.tags + ", photoAuthor=" + this.photoAuthor + ", photoAuthorUrl=" + this.photoAuthorUrl + ", price=" + this.price + ", reviewScore=" + this.reviewScore + ", reviewCount=" + this.reviewCount + ", stockQuantity=" + this.stockQuantity + ", dateAdded=" + this.dateAdded + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Item.ItemBuilder builder() {
        return new Item.ItemBuilder();
    }

    /**
     * Unique identifier for the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    /**
     * Index of the item in the collection
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public short getIndex() {
        return this.index;
    }

    /**
     * URL of the item's image
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Name of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    /**
     * Publisher of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublisher() {
        return this.publisher;
    }

    /**
     * Description of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Category of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    /**
     * Tags associated with the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<String> getTags() {
        return this.tags;
    }

    /**
     * Author of the item's photo
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoAuthor() {
        return this.photoAuthor;
    }

    /**
     * URL of the photo's author
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoAuthorUrl() {
        return this.photoAuthorUrl;
    }

    /**
     * Price of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getPrice() {
        return this.price;
    }

    /**
     * Review score of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getReviewScore() {
        return this.reviewScore;
    }

    /**
     * Number of reviews for the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public short getReviewCount() {
        return this.reviewCount;
    }

    /**
     * Quantity of the item in stock
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public short getStockQuantity() {
        return this.stockQuantity;
    }

    /**
     * Date the item was added to the collection
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Date getDateAdded() {
        return this.dateAdded;
    }

    /**
     * Unique identifier for the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * Index of the item in the collection
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIndex(final short index) {
        this.index = index;
    }

    /**
     * URL of the item's image
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Name of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Publisher of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublisher(final String publisher) {
        this.publisher = publisher;
    }

    /**
     * Description of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Category of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    /**
     * Tags associated with the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTags(final Set<String> tags) {
        this.tags = tags;
    }

    /**
     * Author of the item's photo
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoAuthor(final String photoAuthor) {
        this.photoAuthor = photoAuthor;
    }

    /**
     * URL of the photo's author
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoAuthorUrl(final String photoAuthorUrl) {
        this.photoAuthorUrl = photoAuthorUrl;
    }

    /**
     * Price of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final float price) {
        this.price = price;
    }

    /**
     * Review score of the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReviewScore(final float reviewScore) {
        this.reviewScore = reviewScore;
    }

    /**
     * Number of reviews for the item
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReviewCount(final short reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * Quantity of the item in stock
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStockQuantity(final short stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * Date the item was added to the collection
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateAdded(final Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Item)) return false;
        final Item other = (Item) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getIndex() != other.getIndex()) return false;
        if (java.lang.Float.compare(this.getPrice(), other.getPrice()) != 0) return false;
        if (java.lang.Float.compare(this.getReviewScore(), other.getReviewScore()) != 0) return false;
        if (this.getReviewCount() != other.getReviewCount()) return false;
        if (this.getStockQuantity() != other.getStockQuantity()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$publisher = this.getPublisher();
        final java.lang.Object other$publisher = other.getPublisher();
        if (this$publisher == null ? other$publisher != null : !this$publisher.equals(other$publisher)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$photoAuthor = this.getPhotoAuthor();
        final java.lang.Object other$photoAuthor = other.getPhotoAuthor();
        if (this$photoAuthor == null ? other$photoAuthor != null : !this$photoAuthor.equals(other$photoAuthor)) return false;
        final java.lang.Object this$photoAuthorUrl = this.getPhotoAuthorUrl();
        final java.lang.Object other$photoAuthorUrl = other.getPhotoAuthorUrl();
        if (this$photoAuthorUrl == null ? other$photoAuthorUrl != null : !this$photoAuthorUrl.equals(other$photoAuthorUrl)) return false;
        final java.lang.Object this$dateAdded = this.getDateAdded();
        final java.lang.Object other$dateAdded = other.getDateAdded();
        if (this$dateAdded == null ? other$dateAdded != null : !this$dateAdded.equals(other$dateAdded)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Item;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getIndex();
        result = result * PRIME + java.lang.Float.floatToIntBits(this.getPrice());
        result = result * PRIME + java.lang.Float.floatToIntBits(this.getReviewScore());
        result = result * PRIME + this.getReviewCount();
        result = result * PRIME + this.getStockQuantity();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $publisher = this.getPublisher();
        result = result * PRIME + ($publisher == null ? 43 : $publisher.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $photoAuthor = this.getPhotoAuthor();
        result = result * PRIME + ($photoAuthor == null ? 43 : $photoAuthor.hashCode());
        final java.lang.Object $photoAuthorUrl = this.getPhotoAuthorUrl();
        result = result * PRIME + ($photoAuthorUrl == null ? 43 : $photoAuthorUrl.hashCode());
        final java.lang.Object $dateAdded = this.getDateAdded();
        result = result * PRIME + ($dateAdded == null ? 43 : $dateAdded.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Item(id=" + this.getId() + ", index=" + this.getIndex() + ", imageUrl=" + this.getImageUrl() + ", name=" + this.getName() + ", publisher=" + this.getPublisher() + ", description=" + this.getDescription() + ", category=" + this.getCategory() + ", tags=" + this.getTags() + ", photoAuthor=" + this.getPhotoAuthor() + ", photoAuthorUrl=" + this.getPhotoAuthorUrl() + ", price=" + this.getPrice() + ", reviewScore=" + this.getReviewScore() + ", reviewCount=" + this.getReviewCount() + ", stockQuantity=" + this.getStockQuantity() + ", dateAdded=" + this.getDateAdded() + ")";
    }
}
