package org.troy.capstone.annotations;

import java.lang.annotation.Documented;
import static java.lang.annotation.ElementType.CONSTRUCTOR;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import java.lang.annotation.Retention;
import static java.lang.annotation.RetentionPolicy.RUNTIME;
import java.lang.annotation.Target;

//Code sourced from https://www.baeldung.com/jacoco-report-exclude

/**
 * Indicates that the annotated element was generated by a tool or process.
 * This annotation is used to exclude code from JaCoCo coverage analysis.
 * 
 * JaCoCo automatically excludes any code annotated with @Generated from coverage reports.
 */
@Documented
@Retention(RUNTIME)
@Target({TYPE, METHOD, CONSTRUCTOR})
public @interface Generated {
}